version: '3.8'

services:

  # Frontend Web
  frontend:
    build:
      context: ./smartumroh-tourguide
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${BACKEND_URL}
        VITE_LIVEKIT_URL: wss://${LIVEKIT_DOMAIN}
    container_name: smartumroh-muthowif-app-prod
    depends_on:
      - backend
    ports:
      - "8650:80"
    restart: unless-stopped

  # Backend Next.js API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartumroh-backend-prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - livekit
    ports:
      - "8651:8651"
    restart: unless-stopped

  # LiveKit Server
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server-prod
    command: --node-ip=0.0.0.0 --redis.address=redis:6379
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    ports:
      - "7880:7880"
      - "7881:7881/udp"
    restart: unless-stopped

  # Redis (dibutuhkan LiveKit Production)
  redis:
    image: redis:7-alpine
    container_name: livekit-redis-prod
    restart: unless-stopped

  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: smartumroh-muthowif-db-prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=StrongProdPassword123
      - POSTGRES_DB=smartumroh
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_prod:
